dataset_path: 
  train: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/archive/try4/*train*.parquet
  val: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/archive/try4/*val*parquet
  test: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/archive/try4/*test*parquet
tokenizer: mine
sequence_dictionary_path: /cmnfs/data/proteomics/shabaz_exotic/processed/parquet/allinone/archive/try4/token_dictionary.txt
ion_counts_path: /cmnfs/proj/shabaz/model/2025-02-06_12-16-20/ion_counts.tab
method_list: [ECD,EID,UVPD,HCD,ETciD]
instrument_list:
pep_length: [6, 30]
charge: [1, 6]
batch_size: 100
num_workers: 12
buffer_size: 10000

